### ISSUE TITLE
Package Control.

### ISSUE THREAD

**Issue by ctf0** [mashaal/wild-cherry#1]
it looks sick ,needs a couple of tweaking but over all looks nice ,u should put it up on PC.

**Comment by mashaal** [comment]
Thanks, Package Control is definitely in the cards- just need to find some time to work out the last kinks and submit :crystal_ball:

**Comment by ctf0** [comment]
i liked enough that i had to tinker with so i made some changes & cleanups ,check if u want.

**Comment by mashaal** [comment]
Looks amazing! Will you send me a pull request when you're finished? Thanks! :koala:

**Comment by mashaal** [comment]
https://packagecontrol.io/packages/Wild%20Cherry !

**Comment by ctf0** [comment]
thanx ,kinda lost with the folder structure but still thanx for the mention and the PC.
