### ISSUE TITLE
More configs?

### ISSUE THREAD

**Issue by Efreak** [mashaal/wild-cherry#10]
Any chance of configs for notepad++, putty, Visual Studio?. I realize these are windows programs and you're likely on a mac (iTerm/Sublime), but it would be pretty great to have these available on windows. I'm happy to test, or if you can give a simple color listing, I'm willing to try and work out something. Putty, at least, should be relatively easy.

**Comment by mashaal** [comment]
Hello Efreak,

Unfortunately, I am unfamiliar with all of those programs. I did do a quick google search, and found a sublime to notepad++ theme converter. I haven't tested, but here is the file it output.

NOTEPAD++: https://www.dropbox.com/s/m6lwwy5ybhmm1bq/wild_cherry.stylers.xml?dl=0

If it works could you please take a screenshot? I'll add it to the repo and give you credit :boat:

Also, If you'd like to have a go at converting for putty/visual studio- submit a pull request and I'll merge them in as well! 🏇🏇🏇

**Comment by Efreak** [comment]
Ah. I was looking for a sublime->npp converter, I couldn't find one. Maybe I didn't do a good search. I submitted a theme and some changes in #11. You can export more definitions from [terminal.sexy](https://terminal.sexy/#HxYm____CZvX2UCFKrJQ_9FviDzcD526T12V__jdCZvX2UCEKrJQ_9FviDzbCZvXT12V__je).

**Comment by Efreak** [comment]
I still haven't found anything for converting to VS easily, however I found a bunch of tools for converting from textmate themes to other programs I *don't* use, if anyone else is interested:
- [TextMate to IntelliJ](https://github.com/JetBrains/colorSchemeTool)
- [Textmate to Vim, JEdit and Kate/KWrite](https://github.com/sickill/coloration)
- [TextMate to emacs](https://code.google.com/p/tm-to-emacs-theme/)
- [TextMate to XCode](http://web.archive.org/web/20080914032549/http://francix.org/Downloas/download.html) (dead site->webarchive)
- [TextMate to CodeMirror (CSS)](https://github.com/codio/tmthemeConverter)
- [TextMate to Pacu](http://www.cyblogic.com/en/charcoal/theme/converter)
- [Sublime to LiteIDE](https://github.com/Unknwon/sublite)


Amazing what you can find once you figure out how to search for it. I was trying to find sublime->X, not textmate->X.

**Comment by Efreak** [comment]
I generated a theme using studiostyl.es, but I'm not really very happy with it. It's *very* difficult to create a full visual studio theme, as it doesn't pick any colors on its own. You have to set colors for [*everything*](http://imgur.com/a/sLw1w) if you want a nice theme.

You can preview what I have by going to [studiostyl.es](https://studiostyl.es) and importing [this gist](https://gist.github.com/59ee185c9872671f6bea) at the bottom. Right now my theme is about half wild-cherry and half solarized-dark, and looks worse than it sounds.

**Comment by mashaal** [comment]
Thats actually not looking too bad! I think I used the Dracula theme as a base when I first started working on Wild Cherry.

Thanks 🐝🐝
