### ISSUE TITLE
Chrome Dev Tools theme?

### ISSUE THREAD

**Issue by b-d-m-p** [mashaal/wild-cherry#14]
Hi, 

I just asked you if it was possible to do it for FirefoxDeveloperEdition, which would be awesome, but I do use Chrome Dev Tools more, and I didn't know it, but it seems you can make themes for Chrome Dev Tools too. I would be very into having Wild Cherry for that. 

Here's a Chrome Dev Tools theme for your reference: https://chrome.google.com/webstore/detail/devtools-theme-zero-dark/bomhdjeadceaggdgfoefmpeafkjhegbo

Cheers.

**Comment by mashaal** [comment]
Thanks for your request, I will merge this with your other issue. https://github.com/mashaal/wild-cherry/issues/13

️️🐳️ 🚴
