### ISSUE TITLE
I am loving wild-cherry

### ISSUE THREAD

**Issue by antwonlee** [mashaal/wild-cherry#17]
So, I love having this as an iterm theme.  Is there a vim theme?

**Comment by mashaal** [comment]
Thanks for your request (and love) antwonlee.

I'm not very familiar with vim- but i found this package that converts textmate themes to vim. You may be able to convert the `wild-cherry.tmTheme` in the root directory. If you want to have a go -- submit a pull request and I'll merge it into the repo. (be sure to include a screenshot)

Thanks! 👭👭👭👭👭👭

**Comment by antwonlee** [comment]
Thanks so much, I will give it a try.  This theme makes my working day more happier.  Thanks!
