### ISSUE TITLE
Misaligned text vs icon

### ISSUE THREAD

**Issue by vaff** [mashaal/wild-cherry#21]
Any clue what I've done to make it misalign like this?

![screen shot 2016-06-17 at 11 00 16](https://cloud.githubusercontent.com/assets/351447/16145799/e14bacee-347a-11e6-987d-48201176a7f8.png)

![screen shot 2016-06-17 at 11 06 34](https://cloud.githubusercontent.com/assets/351447/16145906/967a92d8-347b-11e6-8d37-53783d8e0e56.png)

I'm using Robot Mono for Powerline at 14px in iTerm2 build 3.0.2

**Comment by mashaal** [comment]
you can try adjusting the vertical spacing in the font options?

here are my settings, it should match what is in the readme.

![screen shot 2016-06-18 at 7 54 13 am](https://cloud.githubusercontent.com/assets/6100364/16165894/07058aae-352a-11e6-8a69-a4fd2e2e0ec0.png)

**Comment by vaff** [comment]
I tried that. But it didn't seam to do anything. Instead I made the none-ASCII font smaller. It works. But the powerline arrows look a bit funky. Beeing smaller then then line.

Maybe I should fiddle with it a bit more. I will report back

**Comment by vaff** [comment]
Couldn't make it work. I will just run with the solution I found.
