### ISSUE TITLE
Hi theme creator, is there a way for remove the background from the prompt?

### ISSUE THREAD

**Issue by maldad** [mashaal/wild-cherry#24]
I can't get the emojis show properly (with color).
So the prompt could be transparent? or only have the info and emojis?
 
![screenshot_20160715_213103](https://cloud.githubusercontent.com/assets/11675538/16892284/76f0f47a-4ad3-11e6-91ac-7d4d5e8819f0.png)

**Comment by mashaal** [comment]
what OS is that? 🌵

**Comment by maldad** [comment]
it's Linux Chakra

**Comment by mashaal** [comment]
Hmm, maybe there is a linux system setting that allows full-colour emoji? Alternatively, you could remove the background colours from the prompts (or set them to be the same dark purple colour as the background).

You can change how colours are defined in `zsh/wild-cherry.zsh`

![screen shot 2016-07-19 at 1 45 25 pm](https://cloud.githubusercontent.com/assets/6100364/16938005/58d76f50-4db7-11e6-8fba-23fd19041067.png)

**Comment by mashaal** [comment]
Have a look into this for colour emojis -- seems you can install it system-wide!

https://github.com/eosrei/emojione-color-font

**Comment by maldad** [comment]
Thanks, I've installed that font already, because this was the first issue with my system:

![image](https://cloud.githubusercontent.com/assets/11675538/16938431/90ee7336-4d3d-11e6-8bb2-3c566f46a7c0.png)

But now I could modify the colors of the prompt as you said above, thanks a lot!

**Comment by maldad** [comment]
By the way, looks great on solarized light, thanks again :)

![image](https://cloud.githubusercontent.com/assets/11675538/16938691/2d41e34c-4d40-11e6-8d26-1ccb17e89b6d.png)

**Comment by mashaal** [comment]
sacrilege! 😶 👻 👻 ⛪️
