### ISSUE TITLE
iTerm instructions are incomplete

### ISSUE THREAD

**Issue by wraybowling** [mashaal/wild-cherry#26]
Let's pretend I don't know what you're doing without you saying so explicitly.

Starting from scratch, the .itermcolors file only changes what the file extension suggests: colors. There are no emoji, or even changes to how messages appear in the terminal.

You're missing some steps, clearly.

**Comment by mashaal** [comment]
You have to install ZSH, and activate the wild-cherry.zsh theme.

I agree it could be more explicit -- I will see what I can do.

If you happen to get zsh working, please think about submitting a pull request to update the instructions, it would help out massively! 🚴👯🚴👯🚴👯

**Comment by wraybowling** [comment]
![screen shot 2016-10-13 at 3 14 54 pm](https://cloud.githubusercontent.com/assets/1120619/19363273/d2512cf2-9157-11e6-8bf4-f1875c63b05c.png)

This got ZSH running as part of a Wild Cherry profile. None of the other features are to be seen though.

**Comment by mashaal** [comment]
You have to enable the wild_cherry theme in the `~/.zshrc` file -- here is clearer instructions on how to update zsh themes -- https://github.com/robbyrussell/oh-my-zsh#themes

The iTerm theme is only for colours -- the .zsh theme is for all of the formatting and emojis. 🙏

**Comment by mashaal** [comment]
I have added a note to the iTerm instructions which refer to the Zsh instructions. Both are required for usage, I hope that will solve any confusion going forward. ⛅️
