### ISSUE TITLE
Does not render correctly in Terminal

### ISSUE THREAD

**Issue by acgillette** [mashaal/wild-cherry#30]
Hi, I wasn't sure if this was where I was supposed to post this! I installed wild-cherry and it almost works except it won't render certain symbols in it, seen here: http://imgur.com/a/iTlkQ

I have powerline installed as well as the fonts, I just have no idea what's going on.

**Comment by mashaal** [comment]
Is this screenshot from iTerm? I think they have changed their font preferences in a recent update. Could you try checking Non-ASCII font and manually setting that one to be powerline as well?  I found that I had to set the font in both locations. Screenshot below.

<img width="408" alt="screen shot 2017-02-09 at 2 25 46 pm" src="https://cloud.githubusercontent.com/assets/6100364/22768108/ddf74800-eed3-11e6-8e71-ca135fff3d7d.png">

**Comment by acgillette** [comment]
Ah sorry I forgot to say where this is! It's actually in zsh.

**Comment by mashaal** [comment]
I think the font's will need to be set in your terminal app -- I built it with iTerm in mind, and I haven't had heaps of luck getting it looking proper in others (terminal, hyper, etc).

**Comment by mashaal** [comment]
I think the font's will need to be set in your terminal app -- I built it with iTerm in mind, and I haven't had heaps of luck getting it looking proper in others (terminal, hyper, et).

**Comment by acgillette** [comment]
Ohhh ok, is there a specific font I need to set up in zsh?

**Comment by mashaal** [comment]
Yeah, the arrows are the only thing that those powerline fonts include -- for some reason your terminal is not properly rendering the font. There are a bunch of powerline fonts that you could try https://github.com/powerline/fonts 

Maybe try another, and look into your terminal preferences for font options.

**Comment by lavaldi** [comment]
Hi, with Hack font is solved 👌

**Comment by THoisington** [comment]
Hack font also fixed this issue for me.

**Comment by mashaal** [comment]
Thanks @lavaldi and @THoisington!
