### ISSUE TITLE
how to personalize the theme

### ISSUE THREAD

**Issue by ctf0** [mashaal/wild-cherry#31]
is it possible to have something like that ?

![test](https://cloud.githubusercontent.com/assets/7388088/23260104/f915e956-f9d8-11e6-8503-facc722f92af.jpg)

**Comment by mashaal** [comment]
Yes, you will have to edit the zsh-theme file, there is a config for how `TIME` displays at the top of the file- and the output for what displays for the `TIME` is on line 357. To achieve that look, you could probably delete the crystal ball emoji and the reference to Date(hour, minute, second).

https://github.com/mashaal/wild-cherry/blob/master/zsh/wild-cherry.zsh-theme#L357

**Comment by ctf0** [comment]
awesome, would that suffice for the other parts as well ?

**Comment by mashaal** [comment]
All of the zsh-theme settings can be controlled from there. Which emojis display, what order they display in, etc.
