### ISSUE TITLE
Wild Cherry for DuckDuckGo

### ISSUE THREAD

**Issue by peacegiverman** [mashaal/wild-cherry#32]
Here's my version of wild cherry for DuckDuckGo

![Wild Cherry in DuckDuckGo](http://i.imgur.com/teuzKc5.png)

Feel free to add this bookmarklet to the readme if you like it.

    https://duckduckgo.com/?k5=2&kp=-1&kaj=m&k7=2B1F32&kj=4a1386&kx=e15d97&k9=ffb86c&kaa=0AACC5

**Comment by mashaal** [comment]
wow, thanks -- i am myself an avid duckduckgo user -- do you want to pull request a screenshot and link in the readme? will merge 100%!
