### ISSUE TITLE
[iTerm2] hard to see text under cursor

### ISSUE THREAD

**Issue by chaopeng** [mashaal/wild-cherry#35]
<img width="153" alt="screen shot 2017-05-05 at 10 15 23" src="https://cloud.githubusercontent.com/assets/3053989/25749233/ca9c420c-317b-11e7-8212-0bd9afcdbbb1.png">

Maybe we should change `Cursor Text Color` to `#ffffff`
https://github.com/mashaal/wild-cherry/blob/master/iterm/wild-cherry.itermcolors#L176

**Comment by mashaal** [comment]
great idea! want to open a pull request with this? 🌈🌵

**Comment by mashaal** [comment]
closed with https://github.com/mashaal/wild-cherry/pull/36
