### ISSUE TITLE
Atom theme

### ISSUE THREAD

**Issue by nicolasiensen** [mashaal/wild-cherry#4]
I would love to use this theme on [Atom](https://atom.io/)!

**Comment by mashaal** [comment]
Hey Nicolas- Thanks for the interest; I just used the theme converter that Atom provides to get the syntax working. It's now added to the repository- unfortunately I do not know how easy it is to convert the UI?

**Comment by nicolasiensen** [comment]
Awesome! I don't know if there is an easy way to customize the Atom UI.

**Comment by mashaal** [comment]
Hey Nicolas, 

I've made the jump over to Atom as well- and pushed heaps of changes to this package- works really nicely with the Isotope UI theme!

:rocket: 

![ATOM](https://raw.githubusercontent.com/mashaal/wild-cherry/master/images/atom.png)

**Comment by nicolasiensen** [comment]
Sooooo cool!

**Comment by mashaal** [comment]
Nice! Isotope lets you change the side panel bg color as well- in Isotope settings, it's rgb 43, 31, 51 to match that same purple color- I'll add that to the readme file.
